### ISSUE TITLE
dev `[ERROR] Could not read from file: D:\@siteData`

### ISSUE THREAD

**Issue by flaribbit** [flaribbit/vitepress-theme-sakura#1]
```
X [ERROR] Could not read from file: D:\@siteData

    node_modules/.pnpm/vitepress@0.22.4_sass@1.52.0/node_modules/vitepress/dist/client/app/data.js:2:31:
      2 │ import serializedSiteData from '@siteData';
        ╵                                ~~~~~~~~~~~

下午2:06:52 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/vitepress@0.22.4_sass@1.52.0/node_modules/vitepress/dist/client/app/data.js:2:31: ERROR: Could not read from file: D:\@siteData
    at failureErrorWithLog (D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:1603:15)
    at D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:1249:28
    at runOnEndCallbacks (D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:1247:7)
    at D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:1356:14
    at D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (D:\proj\flaribbit.github.io\node_modules\.pnpm\esbuild@0.14.39\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
Vite Error, /node_modules/.vite/deps/vitepress-theme-sakura.js?v=e8f3436e optimized info should be defined
Vite Error, /node_modules/.vite/deps/vitepress-theme-sakura.js?v=e8f3436e optimized info should be defined (x2)
```

**Comment by houyaowei** [comment]
怎么解决的？我也出现这个问题了
